[platformio]
default_envs = generic-esp32-s3
boards_dir = boards

[env:generic-esp32-s3]
platform = espressif32@6.12.0
board = esp32-s3-generic-4mb
framework = arduino
monitor_speed = 115200
upload_speed = 460800
build_unflags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1

; Native USB must run in device/OTG mode for USB HID.
build_flags =
    -DARDUINO_USB_MODE=0
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DCORE_DEBUG_LEVEL=1

lib_deps =
    h2zero/NimBLE-Arduino@2.3.7
